AllCops:
  Exclude:
    - 'vendor/bundler/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
  RunRailsCops: true

# Configuration parameters: AllowSafeAssignment.
Lint/AssignmentInCondition:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: true

Lint/UnderscorePrefixedVariableName:
  Enabled: true

inherit_from: .rubocop_todo.yml
