AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
  RunRailsCops: true
  DisplayCopNames: true

# Configuration parameters: AllowSafeAssignment.
Lint/AssignmentInCondition:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: true

Lint/UnderscorePrefixedVariableName:
  Enabled: true

# FIXME
Rails/TimeZone:
  Enabled: false

# FIXME

inherit_from: .rubocop_fast.yml
#inherit_from: .rubocop_todo.yml
