# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1aa584189fadbfc853c79ff3a3040503f709e560de1bf5227e1577acf2371a0cad5fa33139dfc29d82713f0b3a1dc6f60fa94540c98f88bce625dceafc6c1879

test:
  secret_key_base: 0224741559bf9d64e54ca660c97329d6494cc83ba9a85b160a6b63aab6542acccfb41585da30bac5d24cb5779ac4fc55a6443a670919f4ed0e039e638717f499

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
